-- Private administrator CRM. Additive and safe to rerun before application startup.
BEGIN;

CREATE TABLE IF NOT EXISTS prospect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(200) NOT NULL,
    country_code VARCHAR(2) NOT NULL,
    language VARCHAR(16),
    email VARCHAR(254),
    website VARCHAR(2000),
    instagram_handle VARCHAR(30),
    group_key VARCHAR(200),
    source_url VARCHAR(2000),
    source_type VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_activity_at TIMESTAMP WITH TIME ZONE,
    last_contact_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_prospect_email UNIQUE(email),
    CONSTRAINT uq_prospect_instagram UNIQUE(instagram_handle)
);
CREATE INDEX IF NOT EXISTS idx_prospect_status_country ON prospect(status, country_code);
CREATE INDEX IF NOT EXISTS idx_prospect_group ON prospect(group_key);

CREATE TABLE IF NOT EXISTS prospect_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id BIGINT NOT NULL REFERENCES prospect(id),
    channel VARCHAR(16) NOT NULL,
    type VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    subject VARCHAR(300),
    body TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    external_id VARCHAR(200),
    attachment_name VARCHAR(255),
    source_url VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    recipient_email VARCHAR(254),
    group_key VARCHAR(200),
    CONSTRAINT uq_prospect_activity_external UNIQUE(external_id)
);
CREATE INDEX IF NOT EXISTS idx_prospect_activity_timeline ON prospect_activity(prospect_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_prospect_activity_email_day ON prospect_activity(channel, status, occurred_at);

CREATE TABLE IF NOT EXISTS prospect_outreach_lock (id BIGINT PRIMARY KEY);
INSERT INTO prospect_outreach_lock(id) VALUES (1) ON CONFLICT (id) DO NOTHING;

COMMIT;
