-- Credits the supplier still owes on a container ("Tegoed leverancier"): a short delivery, damage,
-- a wrong price. Additive and rerunnable: one new table with its indexes; no existing table, row or
-- payment changes. An offset credit points at the supplier payment it became on another container
-- (offset_payment_id); purchase_payment itself stays untouched.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE IF NOT EXISTS purchase_supplier_credit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    noted_on date NOT NULL,
    amount numeric(19,2) NOT NULL CHECK (amount > 0),
    currency varchar(8) NOT NULL,
    amount_eur numeric(19,2) NOT NULL CHECK (amount_eur > 0),
    reason varchar(16) NOT NULL,
    note varchar(500),
    status varchar(16) NOT NULL,
    settled_on date,
    offset_order_id bigint,
    offset_payment_id bigint CONSTRAINT uq_purchase_supplier_credit_offset_payment UNIQUE,
    actor varchar(255),
    recorded_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS purchase_supplier_credit_order_idx ON purchase_supplier_credit (order_id);
CREATE INDEX IF NOT EXISTS purchase_supplier_credit_offset_idx ON purchase_supplier_credit (offset_order_id);

COMMIT;
