-- Append-only operational activity log.
--
-- Accounts remain deployment configuration, so actor names are immutable
-- snapshots rather than foreign keys. No credentials or request payloads are
-- stored. This migration is additive, rerunnable, and safe before application code.

begin;

create table if not exists activity_log (
    id bigint generated by default as identity primary key,
    occurred_at timestamp with time zone not null,
    actor_username varchar(64) not null,
    actor_display_name varchar(100) not null,
    action varchar(64) not null,
    entity_type varchar(64) not null,
    entity_id varchar(100),
    entity_label varchar(255),
    summary varchar(500) not null,
    changes_json varchar(16000)
);

-- CREATE TABLE IF NOT EXISTS does not add new columns to an existing table.
-- Keep this base migration independently rerunnable for environments that
-- already installed the original activity-log schema.
alter table activity_log
    add column if not exists changes_json varchar(16000);

create index if not exists idx_activity_log_occurred_at
    on activity_log (occurred_at);
create index if not exists idx_activity_log_actor
    on activity_log (actor_username);
create index if not exists idx_activity_log_entity
    on activity_log (entity_type, entity_id);

commit;
