-- One-time reviewed, localized family tags for every ERP family present on 22 September 2026.
-- Stable family keys resolve the correct rows in PROD and TST; their numeric IDs differ.
-- Only base and translated tags are changed. Every variant inherits its family tags.
-- No names, photos, publication status, dimensions, commercial data or identities change.
-- The audit marker makes re-runs preserve any later manual tag edits.
begin;
set local lock_timeout = '15s';
set local statement_timeout = '120s';

create table if not exists catalog_data_patch (
    patch_key varchar(120) primary key,
    applied_at timestamptz not null default now(),
    affected_rows integer not null,
    before_state jsonb not null
);

create temporary table localized_family_tags_seed_20260922 (
    family_key varchar(255) primary key,
    base_tags jsonb not null,
    translated_tags jsonb not null
) on commit drop;
insert into localized_family_tags_seed_20260922 values
    ('rose-diamonds-within-display', '["preserved roses", "faceted case", "fragrance", "counter display"]'::jsonb, '{"NL": ["gepreserveerde rozen", "facetdoos", "geurbeleving", "toonbankdisplay"], "EN": ["preserved roses", "faceted case", "fragrance", "counter display"], "FR": ["roses stabilisées", "boîte à facettes", "parfum", "présentoir de comptoir"], "DE": ["konservierte Rosen", "facettierte Box", "Duft", "Thekendisplay"], "ES": ["rosas preservadas", "caja facetada", "fragancia", "expositor de mostrador"], "PL": ["róże stabilizowane", "pudełko z fasetami", "zapach", "ekspozytor na ladę"], "PT": ["rosas preservadas", "caixa facetada", "fragrância", "expositor de balcão"], "TR": ["solmayan güller", "fasetli kutu", "koku", "tezgâh standı"], "EL": ["διατηρημένα τριαντάφυλλα", "πολύεδρη θήκη", "άρωμα", "σταντ πάγκου"]}'::jsonb),
    ('preserved-single-rose-in-display', '["preserved roses", "stem roses", "12 pieces per display"]'::jsonb, '{"NL": ["gepreserveerde rozen", "steelrozen", "12 stuks per display"], "EN": ["preserved roses", "stem roses", "12 pieces per display"], "FR": ["roses stabilisées", "roses sur tige", "12 pièces par présentoir"], "DE": ["konservierte Rosen", "Stielrosen", "12 Stück pro Display"], "ES": ["rosas preservadas", "rosas con tallo", "12 unidades por expositor"], "PL": ["róże stabilizowane", "róże na łodydze", "12 sztuk w ekspozytorze"], "PT": ["rosas preservadas", "rosas com haste", "12 unidades por expositor"], "TR": ["solmayan güller", "saplı güller", "stant başına 12 adet"], "EL": ["διατηρημένα τριαντάφυλλα", "τριαντάφυλλα με μίσχο", "12 τεμάχια ανά σταντ"]}'::jsonb),
    ('preserved-bowl-rose', '["preserved roses", "rose bowl", "M", "8 pieces per display"]'::jsonb, '{"NL": ["gepreserveerde rozen", "rozenbowl", "M", "8 stuks per display"], "EN": ["preserved roses", "rose bowl", "M", "8 pieces per display"], "FR": ["roses stabilisées", "rose en coupe", "M", "8 pièces par présentoir"], "DE": ["konservierte Rosen", "Rosenschale", "M", "8 Stück pro Display"], "ES": ["rosas preservadas", "cuenco con rosa", "M", "8 unidades por expositor"], "PL": ["róże stabilizowane", "róża w miseczce", "M", "8 sztuk w ekspozytorze"], "PT": ["rosas preservadas", "taça com rosa", "M", "8 unidades por expositor"], "TR": ["solmayan güller", "kasede gül", "M", "stant başına 8 adet"], "EL": ["διατηρημένα τριαντάφυλλα", "τριαντάφυλλο σε μπολ", "M", "8 τεμάχια ανά σταντ"]}'::jsonb),
    ('bowl-rose-xl', '["preserved roses", "rose bowl", "XL", "6 pieces per display"]'::jsonb, '{"NL": ["gepreserveerde rozen", "rozenbowl", "XL", "6 stuks per display"], "EN": ["preserved roses", "rose bowl", "XL", "6 pieces per display"], "FR": ["roses stabilisées", "rose en coupe", "XL", "6 pièces par présentoir"], "DE": ["konservierte Rosen", "Rosenschale", "XL", "6 Stück pro Display"], "ES": ["rosas preservadas", "cuenco con rosa", "XL", "6 unidades por expositor"], "PL": ["róże stabilizowane", "róża w miseczce", "XL", "6 sztuk w ekspozytorze"], "PT": ["rosas preservadas", "taça com rosa", "XL", "6 unidades por expositor"], "TR": ["solmayan güller", "kasede gül", "XL", "stant başına 6 adet"], "EL": ["διατηρημένα τριαντάφυλλα", "τριαντάφυλλο σε μπολ", "XL", "6 τεμάχια ανά σταντ"]}'::jsonb),
    ('cobalt-blue-roos-in-glazen-stolp', '["preserved roses", "glass dome", "LED lighting", "25 cm"]'::jsonb, '{"NL": ["gepreserveerde rozen", "glazen stolp", "LED-verlichting", "25 cm"], "EN": ["preserved roses", "glass dome", "LED lighting", "25 cm"], "FR": ["roses stabilisées", "cloche en verre", "éclairage LED", "25 cm"], "DE": ["konservierte Rosen", "Glaskuppel", "LED-Beleuchtung", "25 cm"], "ES": ["rosas preservadas", "cúpula de cristal", "iluminación LED", "25 cm"], "PL": ["róże stabilizowane", "szklany klosz", "oświetlenie LED", "25 cm"], "PT": ["rosas preservadas", "redoma de vidro", "iluminação LED", "25 cm"], "TR": ["solmayan güller", "cam fanus", "LED aydınlatma", "25 cm"], "EL": ["διατηρημένα τριαντάφυλλα", "γυάλινη καμπάνα", "φωτισμός LED", "25 cm"]}'::jsonb),
    ('single-rose-in-acryl-glass-box', '["preserved roses", "mirrored base", "acrylic box"]'::jsonb, '{"NL": ["gepreserveerde rozen", "spiegelbasis", "acryldoos"], "EN": ["preserved roses", "mirrored base", "acrylic box"], "FR": ["roses stabilisées", "socle miroir", "boîte en acrylique"], "DE": ["konservierte Rosen", "Spiegelsockel", "Acrylbox"], "ES": ["rosas preservadas", "base de espejo", "caja acrílica"], "PL": ["róże stabilizowane", "lustrzana podstawa", "pudełko akrylowe"], "PT": ["rosas preservadas", "base espelhada", "caixa de acrílico"], "TR": ["solmayan güller", "aynalı taban", "akrilik kutu"], "EL": ["διατηρημένα τριαντάφυλλα", "βάση με καθρέφτη", "ακρυλικό κουτί"]}'::jsonb),
    ('one-rose-in-box', '["preserved roses", "clear box", "ribbon detail"]'::jsonb, '{"NL": ["gepreserveerde rozen", "transparante doos", "lintafwerking"], "EN": ["preserved roses", "clear box", "ribbon detail"], "FR": ["roses stabilisées", "boîte transparente", "finition ruban"], "DE": ["konservierte Rosen", "transparente Box", "Schleifenband"], "ES": ["rosas preservadas", "caja transparente", "acabado con cinta"], "PL": ["róże stabilizowane", "przezroczyste pudełko", "wykończenie wstążką"], "PT": ["rosas preservadas", "caixa transparente", "acabamento com fita"], "TR": ["solmayan güller", "şeffaf kutu", "kurdele detayı"], "EL": ["διατηρημένα τριαντάφυλλα", "διάφανο κουτί", "διακόσμηση με κορδέλα"]}'::jsonb),
    ('hearth-glass-flowerbox', '["preserved roses", "heart shape", "mirror box", "16 roses"]'::jsonb, '{"NL": ["gepreserveerde rozen", "hartvorm", "spiegeldoos", "16 rozen"], "EN": ["preserved roses", "heart shape", "mirror box", "16 roses"], "FR": ["roses stabilisées", "forme de cœur", "boîte miroir", "16 roses"], "DE": ["konservierte Rosen", "Herzform", "Spiegelbox", "16 Rosen"], "ES": ["rosas preservadas", "forma de corazón", "caja con espejo", "16 rosas"], "PL": ["róże stabilizowane", "kształt serca", "pudełko z lustrem", "16 róż"], "PT": ["rosas preservadas", "forma de coração", "caixa espelhada", "16 rosas"], "TR": ["solmayan güller", "kalp şekli", "aynalı kutu", "16 gül"], "EL": ["διατηρημένα τριαντάφυλλα", "σχήμα καρδιάς", "κουτί με καθρέφτη", "16 τριαντάφυλλα"]}'::jsonb),
    ('roses-in-box-16pcs', '["preserved roses", "square flower box", "16 roses"]'::jsonb, '{"NL": ["gepreserveerde rozen", "vierkante flowerbox", "16 rozen"], "EN": ["preserved roses", "square flower box", "16 roses"], "FR": ["roses stabilisées", "boîte à fleurs carrée", "16 roses"], "DE": ["konservierte Rosen", "quadratische Blumenbox", "16 Rosen"], "ES": ["rosas preservadas", "caja de flores cuadrada", "16 rosas"], "PL": ["róże stabilizowane", "kwadratowe pudełko z kwiatami", "16 róż"], "PT": ["rosas preservadas", "caixa de flores quadrada", "16 rosas"], "TR": ["solmayan güller", "kare çiçek kutusu", "16 gül"], "EL": ["διατηρημένα τριαντάφυλλα", "τετράγωνο κουτί λουλουδιών", "16 τριαντάφυλλα"]}'::jsonb),
    ('rose-in-dome-elite', '["preserved roses", "glass dome", "3 roses", "LED lighting", "30 cm"]'::jsonb, '{"NL": ["gepreserveerde rozen", "glazen stolp", "3 rozen", "LED-verlichting", "30 cm"], "EN": ["preserved roses", "glass dome", "3 roses", "LED lighting", "30 cm"], "FR": ["roses stabilisées", "cloche en verre", "3 roses", "éclairage LED", "30 cm"], "DE": ["konservierte Rosen", "Glaskuppel", "3 Rosen", "LED-Beleuchtung", "30 cm"], "ES": ["rosas preservadas", "cúpula de cristal", "3 rosas", "iluminación LED", "30 cm"], "PL": ["róże stabilizowane", "szklany klosz", "3 róż", "oświetlenie LED", "30 cm"], "PT": ["rosas preservadas", "redoma de vidro", "3 rosas", "iluminação LED", "30 cm"], "TR": ["solmayan güller", "cam fanus", "3 gül", "LED aydınlatma", "30 cm"], "EL": ["διατηρημένα τριαντάφυλλα", "γυάλινη καμπάνα", "3 τριαντάφυλλα", "φωτισμός LED", "30 cm"]}'::jsonb),
    ('roses-in-box-9pcs', '["preserved roses", "square flower box", "9 roses"]'::jsonb, '{"NL": ["gepreserveerde rozen", "vierkante flowerbox", "9 rozen"], "EN": ["preserved roses", "square flower box", "9 roses"], "FR": ["roses stabilisées", "boîte à fleurs carrée", "9 roses"], "DE": ["konservierte Rosen", "quadratische Blumenbox", "9 Rosen"], "ES": ["rosas preservadas", "caja de flores cuadrada", "9 rosas"], "PL": ["róże stabilizowane", "kwadratowe pudełko z kwiatami", "9 róż"], "PT": ["rosas preservadas", "caixa de flores quadrada", "9 rosas"], "TR": ["solmayan güller", "kare çiçek kutusu", "9 gül"], "EL": ["διατηρημένα τριαντάφυλλα", "τετράγωνο κουτί λουλουδιών", "9 τριαντάφυλλα"]}'::jsonb),
    ('acrylic-flowerbox', '["preserved roses", "acrylic box", "rose arrangement"]'::jsonb, '{"NL": ["gepreserveerde rozen", "acryldoos", "rozenarrangement"], "EN": ["preserved roses", "acrylic box", "rose arrangement"], "FR": ["roses stabilisées", "boîte en acrylique", "composition de roses"], "DE": ["konservierte Rosen", "Acrylbox", "Rosenarrangement"], "ES": ["rosas preservadas", "caja acrílica", "arreglo de rosas"], "PL": ["róże stabilizowane", "pudełko akrylowe", "kompozycja z róż"], "PT": ["rosas preservadas", "caixa de acrílico", "arranjo de rosas"], "TR": ["solmayan güller", "akrilik kutu", "gül aranjmanı"], "EL": ["διατηρημένα τριαντάφυλλα", "ακρυλικό κουτί", "σύνθεση με τριαντάφυλλα"]}'::jsonb),
    ('rose-in-dome-m', '["preserved roses", "glass dome", "LED lighting", "30 cm"]'::jsonb, '{"NL": ["gepreserveerde rozen", "glazen stolp", "LED-verlichting", "30 cm"], "EN": ["preserved roses", "glass dome", "LED lighting", "30 cm"], "FR": ["roses stabilisées", "cloche en verre", "éclairage LED", "30 cm"], "DE": ["konservierte Rosen", "Glaskuppel", "LED-Beleuchtung", "30 cm"], "ES": ["rosas preservadas", "cúpula de cristal", "iluminación LED", "30 cm"], "PL": ["róże stabilizowane", "szklany klosz", "oświetlenie LED", "30 cm"], "PT": ["rosas preservadas", "redoma de vidro", "iluminação LED", "30 cm"], "TR": ["solmayan güller", "cam fanus", "LED aydınlatma", "30 cm"], "EL": ["διατηρημένα τριαντάφυλλα", "γυάλινη καμπάνα", "φωτισμός LED", "30 cm"]}'::jsonb),
    ('glass-flowerbox', '["preserved roses", "heart shape", "clear box", "16 roses"]'::jsonb, '{"NL": ["gepreserveerde rozen", "hartvorm", "transparante doos", "16 rozen"], "EN": ["preserved roses", "heart shape", "clear box", "16 roses"], "FR": ["roses stabilisées", "forme de cœur", "boîte transparente", "16 roses"], "DE": ["konservierte Rosen", "Herzform", "transparente Box", "16 Rosen"], "ES": ["rosas preservadas", "forma de corazón", "caja transparente", "16 rosas"], "PL": ["róże stabilizowane", "kształt serca", "przezroczyste pudełko", "16 róż"], "PT": ["rosas preservadas", "forma de coração", "caixa transparente", "16 rosas"], "TR": ["solmayan güller", "kalp şekli", "şeffaf kutu", "16 gül"], "EL": ["διατηρημένα τριαντάφυλλα", "σχήμα καρδιάς", "διάφανο κουτί", "16 τριαντάφυλλα"]}'::jsonb),
    ('rose-in-dome-xl', '["preserved roses", "glass dome", "LED lighting", "20 cm"]'::jsonb, '{"NL": ["gepreserveerde rozen", "glazen stolp", "LED-verlichting", "20 cm"], "EN": ["preserved roses", "glass dome", "LED lighting", "20 cm"], "FR": ["roses stabilisées", "cloche en verre", "éclairage LED", "20 cm"], "DE": ["konservierte Rosen", "Glaskuppel", "LED-Beleuchtung", "20 cm"], "ES": ["rosas preservadas", "cúpula de cristal", "iluminación LED", "20 cm"], "PL": ["róże stabilizowane", "szklany klosz", "oświetlenie LED", "20 cm"], "PT": ["rosas preservadas", "redoma de vidro", "iluminação LED", "20 cm"], "TR": ["solmayan güller", "cam fanus", "LED aydınlatma", "20 cm"], "EL": ["διατηρημένα τριαντάφυλλα", "γυάλινη καμπάνα", "φωτισμός LED", "20 cm"]}'::jsonb),
    ('diamond-rose', '["preserved roses", "faceted case", "XL"]'::jsonb, '{"NL": ["gepreserveerde rozen", "facetdoos", "XL"], "EN": ["preserved roses", "faceted case", "XL"], "FR": ["roses stabilisées", "boîte à facettes", "XL"], "DE": ["konservierte Rosen", "facettierte Box", "XL"], "ES": ["rosas preservadas", "caja facetada", "XL"], "PL": ["róże stabilizowane", "pudełko z fasetami", "XL"], "PT": ["rosas preservadas", "caixa facetada", "XL"], "TR": ["solmayan güller", "fasetli kutu", "XL"], "EL": ["διατηρημένα τριαντάφυλλα", "πολύεδρη θήκη", "XL"]}'::jsonb),
    ('soaproos-in-vensterdoos', '["soap roses", "decorative flowers", "window gift box"]'::jsonb, '{"NL": ["zeeprozen", "decoratieve bloemen", "geschenkdoos met venster"], "EN": ["soap roses", "decorative flowers", "window gift box"], "FR": ["roses en savon", "fleurs décoratives", "coffret cadeau avec fenêtre"], "DE": ["Seifenrosen", "Dekoblumen", "Geschenkbox mit Sichtfenster"], "ES": ["rosas de jabón", "flores decorativas", "caja de regalo con ventana"], "PL": ["róże mydlane", "kwiaty dekoracyjne", "pudełko prezentowe z okienkiem"], "PT": ["rosas de sabonete", "flores decorativas", "caixa de presente com janela"], "TR": ["sabun gülleri", "dekoratif çiçekler", "pencereli hediye kutusu"], "EL": ["τριαντάφυλλα από σαπούνι", "διακοσμητικά λουλούδια", "κουτί δώρου με παράθυρο"]}'::jsonb),
    ('soap-rose-box-led', '["soap roses", "decorative flowers", "LED lighting", "gift box"]'::jsonb, '{"NL": ["zeeprozen", "decoratieve bloemen", "LED-verlichting", "geschenkdoos"], "EN": ["soap roses", "decorative flowers", "LED lighting", "gift box"], "FR": ["roses en savon", "fleurs décoratives", "éclairage LED", "coffret cadeau"], "DE": ["Seifenrosen", "Dekoblumen", "LED-Beleuchtung", "Geschenkbox"], "ES": ["rosas de jabón", "flores decorativas", "iluminación LED", "caja de regalo"], "PL": ["róże mydlane", "kwiaty dekoracyjne", "oświetlenie LED", "pudełko prezentowe"], "PT": ["rosas de sabonete", "flores decorativas", "iluminação LED", "caixa de presente"], "TR": ["sabun gülleri", "dekoratif çiçekler", "LED aydınlatma", "hediye kutusu"], "EL": ["τριαντάφυλλα από σαπούνι", "διακοσμητικά λουλούδια", "φωτισμός LED", "κουτί δώρου"]}'::jsonb),
    ('soap-roos-in-box', '["soap roses", "fragrance", "clear box", "ribbon detail"]'::jsonb, '{"NL": ["zeeprozen", "geurbeleving", "transparante doos", "lintafwerking"], "EN": ["soap roses", "fragrance", "clear box", "ribbon detail"], "FR": ["roses en savon", "parfum", "boîte transparente", "finition ruban"], "DE": ["Seifenrosen", "Duft", "transparente Box", "Schleifenband"], "ES": ["rosas de jabón", "fragancia", "caja transparente", "acabado con cinta"], "PL": ["róże mydlane", "zapach", "przezroczyste pudełko", "wykończenie wstążką"], "PT": ["rosas de sabonete", "fragrância", "caixa transparente", "acabamento com fita"], "TR": ["sabun gülleri", "koku", "şeffaf kutu", "kurdele detayı"], "EL": ["τριαντάφυλλα από σαπούνι", "άρωμα", "διάφανο κουτί", "διακόσμηση με κορδέλα"]}'::jsonb),
    ('odoo-heart-flowerbox-28-review', '["flower box", "heart shape", "28 cm"]'::jsonb, '{"NL": ["flowerbox", "hartvorm", "28 cm"], "EN": ["flower box", "heart shape", "28 cm"], "FR": ["boîte à fleurs", "forme de cœur", "28 cm"], "DE": ["Blumenbox", "Herzform", "28 cm"], "ES": ["caja de flores", "forma de corazón", "28 cm"], "PL": ["pudełko z kwiatami", "kształt serca", "28 cm"], "PT": ["caixa de flores", "forma de coração", "28 cm"], "TR": ["çiçek kutusu", "kalp şekli", "28 cm"], "EL": ["κουτί λουλουδιών", "σχήμα καρδιάς", "28 cm"]}'::jsonb),
    ('odoo-dome-15x30-single-review', '["rose in dome", "15 × 30 cm"]'::jsonb, '{"NL": ["roos in stolp", "15 × 30 cm"], "EN": ["rose in dome", "15 × 30 cm"], "FR": ["rose sous cloche", "15 × 30 cm"], "DE": ["Rose unter Kuppel", "15 × 30 cm"], "ES": ["rosa en cúpula", "15 × 30 cm"], "PL": ["róża pod kloszem", "15 × 30 cm"], "PT": ["rosa em redoma", "15 × 30 cm"], "TR": ["fanusta gül", "15 × 30 cm"], "EL": ["τριαντάφυλλο σε καμπάνα", "15 × 30 cm"]}'::jsonb),
    ('foam-half-heart-25', '["foam roses", "artificial roses", "half-heart shape", "25 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "halve hartvorm", "25 cm"], "EN": ["foam roses", "artificial roses", "half-heart shape", "25 cm"], "FR": ["roses en mousse", "roses artificielles", "forme de demi-cœur", "25 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Halbherzform", "25 cm"], "ES": ["rosas de espuma", "rosas artificiales", "forma de medio corazón", "25 cm"], "PL": ["róże piankowe", "sztuczne róże", "kształt połowy serca", "25 cm"], "PT": ["rosas de espuma", "rosas artificiais", "forma de meio coração", "25 cm"], "TR": ["köpük güller", "yapay güller", "yarım kalp şekli", "25 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "σχήμα μισής καρδιάς", "25 cm"]}'::jsonb),
    ('foam-half-heart-40', '["foam roses", "artificial roses", "half-heart shape", "40 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "halve hartvorm", "40 cm"], "EN": ["foam roses", "artificial roses", "half-heart shape", "40 cm"], "FR": ["roses en mousse", "roses artificielles", "forme de demi-cœur", "40 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Halbherzform", "40 cm"], "ES": ["rosas de espuma", "rosas artificiales", "forma de medio corazón", "40 cm"], "PL": ["róże piankowe", "sztuczne róże", "kształt połowy serca", "40 cm"], "PT": ["rosas de espuma", "rosas artificiais", "forma de meio coração", "40 cm"], "TR": ["köpük güller", "yapay güller", "yarım kalp şekli", "40 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "σχήμα μισής καρδιάς", "40 cm"]}'::jsonb),
    ('odoo-preserved-rose-windowbox', '["demo product", "window gift box"]'::jsonb, '{"NL": ["demoproduct", "geschenkdoos met venster"], "EN": ["demo product", "window gift box"], "FR": ["produit de démonstration", "coffret cadeau avec fenêtre"], "DE": ["Demoprodukt", "Geschenkbox mit Sichtfenster"], "ES": ["producto de demostración", "caja de regalo con ventana"], "PL": ["produkt demonstracyjny", "pudełko prezentowe z okienkiem"], "PT": ["produto de demonstração", "caixa de presente com janela"], "TR": ["demo ürün", "pencereli hediye kutusu"], "EL": ["προϊόν επίδειξης", "κουτί δώρου με παράθυρο"]}'::jsonb),
    ('long-stem-rose-box-display', '["preserved roses", "extra-long stem roses", "clear box", "12 pieces per display"]'::jsonb, '{"NL": ["gepreserveerde rozen", "extra lange steelrozen", "transparante doos", "12 stuks per display"], "EN": ["preserved roses", "extra-long stem roses", "clear box", "12 pieces per display"], "FR": ["roses stabilisées", "roses à très longue tige", "boîte transparente", "12 pièces par présentoir"], "DE": ["konservierte Rosen", "Rosen mit extra langem Stiel", "transparente Box", "12 Stück pro Display"], "ES": ["rosas preservadas", "rosas de tallo extralargo", "caja transparente", "12 unidades por expositor"], "PL": ["róże stabilizowane", "róże na bardzo długiej łodydze", "przezroczyste pudełko", "12 sztuk w ekspozytorze"], "PT": ["rosas preservadas", "rosas de haste extralonga", "caixa transparente", "12 unidades por expositor"], "TR": ["solmayan güller", "ekstra uzun saplı güller", "şeffaf kutu", "stant başına 12 adet"], "EL": ["διατηρημένα τριαντάφυλλα", "τριαντάφυλλα με πολύ μακρύ μίσχο", "διάφανο κουτί", "12 τεμάχια ανά σταντ"]}'::jsonb),
    ('foam-bear-25', '["foam roses", "artificial roses", "rose bear", "25 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "rozenbeer", "25 cm"], "EN": ["foam roses", "artificial roses", "rose bear", "25 cm"], "FR": ["roses en mousse", "roses artificielles", "ours en roses", "25 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Rosenbär", "25 cm"], "ES": ["rosas de espuma", "rosas artificiales", "oso de rosas", "25 cm"], "PL": ["róże piankowe", "sztuczne róże", "miś z róż", "25 cm"], "PT": ["rosas de espuma", "rosas artificiais", "urso de rosas", "25 cm"], "TR": ["köpük güller", "yapay güller", "gül ayıcık", "25 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "αρκουδάκι από τριαντάφυλλα", "25 cm"]}'::jsonb),
    ('foam-heart-15', '["foam roses", "artificial roses", "heart shape", "15 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "hartvorm", "15 cm"], "EN": ["foam roses", "artificial roses", "heart shape", "15 cm"], "FR": ["roses en mousse", "roses artificielles", "forme de cœur", "15 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Herzform", "15 cm"], "ES": ["rosas de espuma", "rosas artificiales", "forma de corazón", "15 cm"], "PL": ["róże piankowe", "sztuczne róże", "kształt serca", "15 cm"], "PT": ["rosas de espuma", "rosas artificiais", "forma de coração", "15 cm"], "TR": ["köpük güller", "yapay güller", "kalp şekli", "15 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "σχήμα καρδιάς", "15 cm"]}'::jsonb),
    ('model-113-114', '["test product", "demo product"]'::jsonb, '{"NL": ["testproduct", "demoproduct"], "EN": ["test product", "demo product"], "FR": ["produit de test", "produit de démonstration"], "DE": ["Testprodukt", "Demoprodukt"], "ES": ["producto de prueba", "producto de demostración"], "PL": ["produkt testowy", "produkt demonstracyjny"], "PT": ["produto de teste", "produto de demonstração"], "TR": ["test ürünü", "demo ürün"], "EL": ["δοκιμαστικό προϊόν", "προϊόν επίδειξης"]}'::jsonb),
    ('model-116-117', '["foam roses", "artificial roses", "rose bear", "40 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "rozenbeer", "40 cm"], "EN": ["foam roses", "artificial roses", "rose bear", "40 cm"], "FR": ["roses en mousse", "roses artificielles", "ours en roses", "40 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Rosenbär", "40 cm"], "ES": ["rosas de espuma", "rosas artificiales", "oso de rosas", "40 cm"], "PL": ["róże piankowe", "sztuczne róże", "miś z róż", "40 cm"], "PT": ["rosas de espuma", "rosas artificiais", "urso de rosas", "40 cm"], "TR": ["köpük güller", "yapay güller", "gül ayıcık", "40 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "αρκουδάκι από τριαντάφυλλα", "40 cm"]}'::jsonb),
    ('foam-bear-with-heart-25', '["foam roses", "artificial roses", "rose bear", "heart shape", "25 cm"]'::jsonb, '{"NL": ["foamrozen", "kunstrozen", "rozenbeer", "hartvorm", "25 cm"], "EN": ["foam roses", "artificial roses", "rose bear", "heart shape", "25 cm"], "FR": ["roses en mousse", "roses artificielles", "ours en roses", "forme de cœur", "25 cm"], "DE": ["Schaumstoffrosen", "Kunstrosen", "Rosenbär", "Herzform", "25 cm"], "ES": ["rosas de espuma", "rosas artificiales", "oso de rosas", "forma de corazón", "25 cm"], "PL": ["róże piankowe", "sztuczne róże", "miś z róż", "kształt serca", "25 cm"], "PT": ["rosas de espuma", "rosas artificiais", "urso de rosas", "forma de coração", "25 cm"], "TR": ["köpük güller", "yapay güller", "gül ayıcık", "kalp şekli", "25 cm"], "EL": ["τριαντάφυλλα από αφρώδες υλικό", "τεχνητά τριαντάφυλλα", "αρκουδάκι από τριαντάφυλλα", "σχήμα καρδιάς", "25 cm"]}'::jsonb),
    ('model-119-120', '["preserved roses", "rose in dome", "without gift box", "12 × 25 cm"]'::jsonb, '{"NL": ["gepreserveerde rozen", "roos in stolp", "zonder geschenkdoos", "12 × 25 cm"], "EN": ["preserved roses", "rose in dome", "without gift box", "12 × 25 cm"], "FR": ["roses stabilisées", "rose sous cloche", "sans coffret cadeau", "12 × 25 cm"], "DE": ["konservierte Rosen", "Rose unter Kuppel", "ohne Geschenkbox", "12 × 25 cm"], "ES": ["rosas preservadas", "rosa en cúpula", "sin caja de regalo", "12 × 25 cm"], "PL": ["róże stabilizowane", "róża pod kloszem", "bez pudełka prezentowego", "12 × 25 cm"], "PT": ["rosas preservadas", "rosa em redoma", "sem caixa de presente", "12 × 25 cm"], "TR": ["solmayan güller", "fanusta gül", "hediye kutusu olmadan", "12 × 25 cm"], "EL": ["διατηρημένα τριαντάφυλλα", "τριαντάφυλλο σε καμπάνα", "χωρίς κουτί δώρου", "12 × 25 cm"]}'::jsonb),
    ('rose-in-dome-7x23', '["rose in dome", "slim dome", "gift box", "23 cm"]'::jsonb, '{"NL": ["roos in stolp", "slanke stolp", "geschenkdoos", "23 cm"], "EN": ["rose in dome", "slim dome", "gift box", "23 cm"], "FR": ["rose sous cloche", "cloche élancée", "coffret cadeau", "23 cm"], "DE": ["Rose unter Kuppel", "schlanke Kuppel", "Geschenkbox", "23 cm"], "ES": ["rosa en cúpula", "cúpula esbelta", "caja de regalo", "23 cm"], "PL": ["róża pod kloszem", "smukły klosz", "pudełko prezentowe", "23 cm"], "PT": ["rosa em redoma", "redoma esguia", "caixa de presente", "23 cm"], "TR": ["fanusta gül", "ince fanus", "hediye kutusu", "23 cm"], "EL": ["τριαντάφυλλο σε καμπάνα", "λεπτή καμπάνα", "κουτί δώρου", "23 cm"]}'::jsonb);

do $migration$
declare
    before_tags jsonb;
    base_changes integer;
    translation_changes integer;
    family_matches integer;
begin
    -- Serialize the marker check even if this file is run outside the deployment runner.
    perform pg_advisory_xact_lock(hashtextextended('enrosed:localized-tags-2026-09-22', 0));
    if exists (select 1 from catalog_data_patch where patch_key = 'localized-tags-2026-09-22') then
        return;
    end if;

    -- Family translations use the same family-row lock in the application. Snapshot only
    -- after taking that lock, so rollback evidence reflects the tags actually replaced.
    perform f.id
      from product_family f
      join localized_family_tags_seed_20260922 s on s.family_key = f.familykey
      order by f.id
      for update of f;
    select count(*) into family_matches
      from product_family f
      join localized_family_tags_seed_20260922 s on s.family_key = f.familykey;
    if family_matches = 0 then return; end if;

    select jsonb_agg(
        jsonb_build_object(
            'familyKey', f.familykey,
            'baseTagsJson', f.tagsjson,
            'texts', (
                select jsonb_agg(jsonb_build_object(
                    'language', langs.language,
                    'existed', t.id is not null,
                    'tagsJson', t.tagsjson
                ) order by langs.language)
                from jsonb_object_keys(s.translated_tags) as langs(language)
                left join product_family_text t
                  on t.family_id = f.id and t.language = langs.language
            )
        ) order by f.familykey
    ) into before_tags
    from product_family f
    join localized_family_tags_seed_20260922 s on s.family_key = f.familykey;

    update product_family f
       set tagsjson = s.base_tags::text
      from localized_family_tags_seed_20260922 s
     where f.familykey = s.family_key
       and f.tagsjson is distinct from s.base_tags::text;
    get diagnostics base_changes = row_count;

    insert into product_family_text(family_id, language, tagsjson)
    select f.id, translated.key, translated.value::text
      from product_family f
      join localized_family_tags_seed_20260922 s on s.family_key = f.familykey
      cross join lateral jsonb_each(s.translated_tags) translated
    on conflict (family_id, language) do update
       set tagsjson = excluded.tagsjson
     where product_family_text.tagsjson is distinct from excluded.tagsjson;
    get diagnostics translation_changes = row_count;

    insert into catalog_data_patch(patch_key, affected_rows, before_state)
    values ('localized-tags-2026-09-22', base_changes + translation_changes,
            jsonb_build_object('families', before_tags));
    raise notice 'Localized tags: % families matched, % base lists and % translations updated',
        family_matches, base_changes, translation_changes;
end
$migration$;

commit;
