BEGIN;

CREATE TABLE IF NOT EXISTS partner_advance_quote_snapshot (
    sales_order_id bigint PRIMARY KEY REFERENCES sales_order(id),
    purchase_order_id bigint NOT NULL REFERENCES purchase_order(id),
    financing_pct numeric(9,4) NOT NULL CHECK (financing_pct >= 0 AND financing_pct <= 100),
    agreed_amount_eur numeric(19,2) NOT NULL CHECK (agreed_amount_eur >= 0),
    share_pct numeric(9,4) NOT NULL CHECK (share_pct >= 0 AND share_pct <= 100)
);
CREATE INDEX IF NOT EXISTS partner_advance_quote_purchase_idx ON partner_advance_quote_snapshot(purchase_order_id);

CREATE TABLE IF NOT EXISTS partner_advance_quote_row_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint NOT NULL REFERENCES partner_advance_quote_snapshot(sales_order_id),
    -- An audit reference only: changing an unbilled plan must not change a sent quotation.
    schedule_row_id bigint,
    position integer NOT NULL,
    label varchar(160) NOT NULL,
    percentage numeric(9,4) CHECK (percentage IS NULL OR (percentage > 0 AND percentage <= 100)),
    amount_eur numeric(19,2) NOT NULL CHECK (amount_eur > 0),
    due_date date,
    UNIQUE (sales_order_id, position)
);

COMMIT;
