BEGIN;
ALTER TABLE sales_payment ADD COLUMN IF NOT EXISTS bank_account varchar(120);
ALTER TABLE sales_payment DROP CONSTRAINT IF EXISTS sales_payment_positive_amount;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='sales_payment_nonzero_amount' AND conrelid='sales_payment'::regclass) THEN
    ALTER TABLE sales_payment ADD CONSTRAINT sales_payment_nonzero_amount CHECK (amount_eur <> 0);
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS bank_statement_line (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account varchar(120) NOT NULL,
  fingerprint varchar(64) NOT NULL,
  amount_eur numeric(19,2) NOT NULL CHECK (amount_eur <> 0),
  booked_at timestamptz NOT NULL,
  time_zone varchar(64) NOT NULL,
  reference varchar(500), counterparty varchar(300),
  recorded_at timestamptz NOT NULL, actor varchar(255),
  sales_payment_id bigint UNIQUE REFERENCES sales_payment(id),
  sales_order_id bigint REFERENCES sales_order(id), allocated_at timestamptz,
  allocation_created_payment boolean NOT NULL DEFAULT false,
  CONSTRAINT bank_statement_account_fingerprint UNIQUE(account,fingerprint)
);
CREATE INDEX IF NOT EXISTS bank_statement_account_date_idx ON bank_statement_line(account,booked_at);
COMMIT;
