BEGIN;

CREATE TABLE IF NOT EXISTS partner_advance_agreement (
    purchase_order_id bigint PRIMARY KEY REFERENCES purchase_order(id),
    partner_customer_id bigint NOT NULL REFERENCES customer(id),
    external_cost_eur numeric(19,2) NOT NULL,
    financing_pct numeric(9,4) NOT NULL CHECK (financing_pct >= 0 AND financing_pct <= 100),
    agreed_amount_eur numeric(19,2) NOT NULL CHECK (agreed_amount_eur >= 0),
    updated_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS partner_advance_instalment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint NOT NULL REFERENCES partner_advance_agreement(purchase_order_id),
    position integer NOT NULL,
    label varchar(160) NOT NULL,
    percentage numeric(9,4),
    amount_eur numeric(19,2) NOT NULL CHECK (amount_eur > 0),
    due_date date,
    sales_order_id bigint UNIQUE REFERENCES sales_order(id),
    CONSTRAINT partner_advance_pct_range CHECK (percentage IS NULL OR (percentage > 0 AND percentage <= 100))
);
CREATE INDEX IF NOT EXISTS partner_advance_instalment_purchase_idx ON partner_advance_instalment(purchase_order_id, position);

ALTER TABLE partner_settlement_snapshot ADD COLUMN IF NOT EXISTS final_settlement boolean;
UPDATE partner_settlement_snapshot SET final_settlement = true WHERE final_settlement IS NULL;
CREATE TABLE IF NOT EXISTS partner_settlement_line_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint NOT NULL REFERENCES partner_settlement_snapshot(sales_order_id),
    product_id bigint NOT NULL REFERENCES product(id),
    quantity integer NOT NULL CHECK (quantity > 0),
    proceeds_eur numeric(19,2) NOT NULL,
    cost_eur numeric(19,2) NOT NULL,
    revenue_eur numeric(19,2) NOT NULL,
    advance_eur numeric(19,2) NOT NULL,
    UNIQUE (sales_order_id, product_id)
);
CREATE INDEX IF NOT EXISTS partner_settlement_line_order_idx ON partner_settlement_line_snapshot(sales_order_id);

COMMIT;
