-- Customer logins for the website quote request: login requests that staff approve or reject,
-- the account per e-mail address, its one-time invitation link and its server-side sessions.
-- Additive and rerunnable: four new tables with their indexes, no existing table is touched.
-- Status, source and language are plain varchars without a constraint on their values, and
-- there are no foreign keys (integrity is kept in the services). Only hashes of link and
-- session tokens are stored. The partial unique index (one open request per e-mail) exists
-- in PostgreSQL only.
begin;

create table if not exists customer_login_request (
    id bigint generated by default as identity primary key,
    reference varchar(32) not null,
    status varchar(16) not null,
    source varchar(16) not null,
    language varchar(4) not null,
    company_name varchar(160) not null,
    company_country_code varchar(2),
    vat_number varchar(32),
    contact_name varchar(120) not null,
    email varchar(254) not null,
    phone varchar(50),
    message varchar(1000),
    customer_id bigint,
    sales_order_id bigint,
    sales_order_number varchar(40),
    account_id bigint,
    repeat_count integer not null default 0,
    later_submissions varchar(8000),
    privacy_accepted_at timestamptz,
    privacy_policy_version varchar(32),
    decided_at timestamptz,
    decided_by varchar(64),
    decision_note varchar(500),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_customer_login_request_reference unique (reference)
);
create index if not exists idx_customer_login_request_status on customer_login_request (status, created_at);
create index if not exists idx_customer_login_request_email on customer_login_request (email);
create index if not exists idx_customer_login_request_customer on customer_login_request (customer_id);
create unique index if not exists uq_customer_login_request_pending_email
    on customer_login_request (email) where status = 'PENDING';

create table if not exists customer_account (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    email varchar(254) not null,
    contact_name varchar(120),
    language varchar(4) not null,
    status varchar(16) not null,
    password_hash varchar(100),
    password_set_at timestamptz,
    last_login_at timestamptz,
    last_link_sent_at timestamptz,
    last_link_error varchar(300),
    created_at timestamptz not null,
    created_by varchar(64) not null,
    updated_at timestamptz not null,
    disabled_at timestamptz,
    disabled_by varchar(64),
    constraint uq_customer_account_email unique (email)
);
create index if not exists idx_customer_account_customer on customer_account (customer_id);

create table if not exists customer_account_token (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    token_hash varchar(64) not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null,
    created_by varchar(64) not null,
    constraint uq_customer_account_token_hash unique (token_hash)
);
create index if not exists idx_customer_account_token_account on customer_account_token (account_id);

create table if not exists customer_session (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    token_hash varchar(64) not null,
    created_at timestamptz not null,
    last_seen_at timestamptz not null,
    expires_at timestamptz not null,
    constraint uq_customer_session_token_hash unique (token_hash)
);
create index if not exists idx_customer_session_account on customer_session (account_id);
create index if not exists idx_customer_session_expiry on customer_session (expires_at);

commit;
