-- A category's own photos: the picture the website and the printed
-- catalogue open a collection with. Rerunnable; the foreign key is added
-- once the category table exists (a completely empty database creates it
-- through the application first).

create table if not exists category_photo (
    id bigint generated by default as identity primary key,
    category_id bigint,
    storage_key varchar(120) not null,
    original_filename varchar(255) not null,
    content_type varchar(120) not null,
    size_bytes bigint not null,
    width_px integer,
    height_px integer,
    position integer not null
);

do $migration$
begin
    if to_regclass('category') is not null and not exists (
        select 1 from pg_constraint
        where conname = 'fk_category_photo_category'
          and conrelid = 'category_photo'::regclass
    ) then
        alter table category_photo
            add constraint fk_category_photo_category
            foreign key (category_id) references category (id) on delete cascade;
    end if;
end
$migration$;

create index if not exists ix_category_photo_category on category_photo (category_id, position);
