-- Additive and repeatable: no business records are deleted or moved by deployment.
BEGIN;

ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS deleted_at timestamp(6) with time zone;
ALTER TABLE purchase_order ADD COLUMN IF NOT EXISTS deleted_at timestamp(6) with time zone;

CREATE TABLE IF NOT EXISTS deleted_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind varchar(16) NOT NULL,
    source_id bigint NOT NULL,
    type varchar(20) NOT NULL,
    number varchar(255),
    partyname varchar(255),
    status varchar(255),
    deleted_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    deletedby varchar(255),
    snapshot_json text NOT NULL,
    order_json text NOT NULL,
    partner_context_json text,
    CONSTRAINT deleted_item_source_unique UNIQUE (source_kind, source_id)
);

CREATE INDEX IF NOT EXISTS deleted_item_expiry_idx ON deleted_item (expires_at, deleted_at);
CREATE INDEX IF NOT EXISTS sales_order_deleted_idx ON sales_order (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS purchase_order_deleted_idx ON purchase_order (deleted_at) WHERE deleted_at IS NOT NULL;

COMMIT;
