-- Supplier-scoped agreement evidence for products.
-- Safe to rerun: creation of the table and indexes is additive and idempotent.
-- Deploy before application code when DB_SCHEMA_STRATEGY=validate. Existing application
-- versions ignore this new table, so the migration is safe to apply independently.

begin;

create table if not exists product_supplier_agreement_photo (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    supplier_id bigint not null,
    storage_key varchar(80) not null,
    original_filename varchar(255) not null,
    content_type varchar(120) not null,
    size_bytes bigint not null,
    width_px integer,
    height_px integer,
    position integer not null,
    caption_en varchar(500)
);

-- Hibernate may already have created the table before this operational script is run.
-- PostgreSQL has no ADD CONSTRAINT IF NOT EXISTS, so guard both constraints explicitly.
do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_supplier_agreement_photo_product'
          and conrelid = 'product_supplier_agreement_photo'::regclass
    ) then
        alter table product_supplier_agreement_photo
            add constraint fk_supplier_agreement_photo_product
            foreign key (product_id) references product (id) on delete cascade;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'uq_product_supplier_agreement_photo_position'
          and conrelid = 'product_supplier_agreement_photo'::regclass
    ) then
        alter table product_supplier_agreement_photo
            add constraint uq_product_supplier_agreement_photo_position
            unique (product_id, supplier_id, position);
    end if;
end
$migration$;

create index if not exists ix_product_supplier_agreement_photo_scope
    on product_supplier_agreement_photo (product_id, supplier_id);

create index if not exists ix_product_supplier_agreement_photo_storage
    on product_supplier_agreement_photo (storage_key);

commit;
