-- Central document and media registry. Additive only: legacy file tables and blobs remain intact.
-- IF NOT EXISTS keeps this safe when a schema was prepared manually; the script is rerunnable.

create table if not exists media_asset (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    kind varchar(20) not null,
    current_version_id bigint,
    archived boolean not null default false,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    created_by varchar(64),
    constraint ck_media_asset_kind check (kind in ('IMAGE', 'DOCUMENT'))
);

create table if not exists media_version (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    version_number integer not null,
    storage_key varchar(80) not null,
    original_filename varchar(255) not null,
    content_type varchar(120) not null,
    size_bytes bigint not null,
    sha256 varchar(64) not null,
    width_px integer,
    height_px integer,
    thumbnail_storage_key varchar(80),
    thumbnail_content_type varchar(120),
    thumbnail_size_bytes bigint,
    thumbnail_width_px integer,
    thumbnail_height_px integer,
    created_at timestamp with time zone not null,
    created_by varchar(64),
    constraint fk_media_version_asset foreign key (asset_id) references media_asset(id) on delete cascade,
    constraint uk_media_version_asset_number unique (asset_id, version_number),
    constraint uk_media_version_sha256 unique (sha256),
    constraint uk_media_version_id_asset unique (id, asset_id),
    constraint ck_media_version_number check (version_number > 0),
    constraint ck_media_version_size check (size_bytes >= 0)
);

create table if not exists media_link (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    target_type varchar(30) not null,
    target_id bigint not null,
    role varchar(20) not null,
    primary_slot integer,
    pinned_version_id bigint,
    legacy_only boolean not null default false,
    created_at timestamp with time zone not null,
    created_by varchar(64),
    constraint fk_media_link_asset foreign key (asset_id) references media_asset(id) on delete cascade,
    constraint fk_media_link_pinned_version foreign key (pinned_version_id, asset_id)
        references media_version(id, asset_id),
    constraint uk_media_link_asset_target_role unique (asset_id, target_type, target_id, role),
    constraint ck_media_link_target_type check (
        target_type in ('PRODUCT', 'PRODUCT_FAMILY', 'PURCHASE_ORDER', 'PLANNER_ITEM')),
    constraint ck_media_link_role check (role in ('CATALOGUE', 'QUOTE', 'INVOICE', 'INTERNAL')),
    constraint ck_media_link_primary_slot check (primary_slot is null or primary_slot = 1)
);

create table if not exists media_legacy_source (
    id bigint generated by default as identity primary key,
    source_type varchar(30) not null,
    source_id bigint not null,
    asset_id bigint not null,
    version_id bigint not null,
    target_type varchar(30) not null,
    target_id bigint not null,
    role varchar(20) not null,
    label varchar(255),
    indexed_at timestamp with time zone not null,
    constraint fk_media_legacy_source_asset foreign key (asset_id) references media_asset(id) on delete cascade,
    constraint fk_media_legacy_source_version foreign key (version_id, asset_id)
        references media_version(id, asset_id),
    constraint uk_media_legacy_source_identity unique (source_type, source_id),
    constraint ck_media_legacy_source_type check (
        source_type in ('PRODUCT_PHOTO', 'FAMILY_PHOTO', 'PURCHASE_DOCUMENT', 'PLANNER_ATTACHMENT')),
    constraint ck_media_legacy_target_type check (
        target_type in ('PRODUCT', 'PRODUCT_FAMILY', 'PURCHASE_ORDER', 'PLANNER_ITEM')),
    constraint ck_media_legacy_role check (role in ('CATALOGUE', 'QUOTE', 'INVOICE', 'INTERNAL'))
);

create table if not exists sales_document_media_snapshot (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    role varchar(20) not null,
    storage_key varchar(80) not null,
    content_type varchar(120) not null,
    original_filename varchar(255) not null,
    media_asset_id bigint,
    media_version_id bigint,
    created_at timestamp with time zone not null,
    constraint uk_sales_document_media_snapshot unique (order_id, product_id, role),
    constraint ck_sales_document_media_role check (role in ('QUOTE', 'INVOICE'))
);

-- CREATE TABLE IF NOT EXISTS does not repair constraints on a table that was prepared manually.
-- Add every integrity rule independently as well, so re-running this script is additive and safe.
do $$
begin
    if not exists (select 1 from pg_constraint where conrelid = 'media_asset'::regclass
            and conname = 'ck_media_asset_kind') then
        alter table media_asset add constraint ck_media_asset_kind
            check (kind in ('IMAGE', 'DOCUMENT'));
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'fk_media_version_asset') then
        alter table media_version add constraint fk_media_version_asset
            foreign key (asset_id) references media_asset(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'uk_media_version_asset_number') then
        alter table media_version add constraint uk_media_version_asset_number
            unique (asset_id, version_number);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'uk_media_version_sha256') then
        alter table media_version add constraint uk_media_version_sha256 unique (sha256);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'uk_media_version_id_asset') then
        alter table media_version add constraint uk_media_version_id_asset unique (id, asset_id);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'ck_media_version_number') then
        alter table media_version add constraint ck_media_version_number check (version_number > 0);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'ck_media_version_size') then
        alter table media_version add constraint ck_media_version_size check (size_bytes >= 0);
    end if;
    if to_regclass('photo_blob') is not null and not exists (
            select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'fk_media_version_storage_blob') then
        alter table media_version add constraint fk_media_version_storage_blob
            foreign key (storage_key) references photo_blob(storageKey) on delete restrict;
    end if;
    if to_regclass('photo_blob') is not null and not exists (
            select 1 from pg_constraint where conrelid = 'media_version'::regclass
            and conname = 'fk_media_version_thumbnail_blob') then
        alter table media_version add constraint fk_media_version_thumbnail_blob
            foreign key (thumbnail_storage_key) references photo_blob(storageKey) on delete restrict;
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'fk_media_link_asset') then
        alter table media_link add constraint fk_media_link_asset
            foreign key (asset_id) references media_asset(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'fk_media_link_pinned_version') then
        alter table media_link add constraint fk_media_link_pinned_version
            foreign key (pinned_version_id, asset_id) references media_version(id, asset_id);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'uk_media_link_asset_target_role') then
        alter table media_link add constraint uk_media_link_asset_target_role
            unique (asset_id, target_type, target_id, role);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'ck_media_link_target_type') then
        alter table media_link add constraint ck_media_link_target_type check (
            target_type in ('PRODUCT', 'PRODUCT_FAMILY', 'PURCHASE_ORDER', 'PLANNER_ITEM'));
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'ck_media_link_role') then
        alter table media_link add constraint ck_media_link_role
            check (role in ('CATALOGUE', 'QUOTE', 'INVOICE', 'INTERNAL'));
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_link'::regclass
            and conname = 'ck_media_link_primary_slot') then
        alter table media_link add constraint ck_media_link_primary_slot
            check (primary_slot is null or primary_slot = 1);
    end if;

    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'fk_media_legacy_source_asset') then
        alter table media_legacy_source add constraint fk_media_legacy_source_asset
            foreign key (asset_id) references media_asset(id) on delete cascade;
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'fk_media_legacy_source_version') then
        alter table media_legacy_source add constraint fk_media_legacy_source_version
            foreign key (version_id, asset_id) references media_version(id, asset_id);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'uk_media_legacy_source_identity') then
        alter table media_legacy_source add constraint uk_media_legacy_source_identity
            unique (source_type, source_id);
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'ck_media_legacy_source_type') then
        alter table media_legacy_source add constraint ck_media_legacy_source_type check (
            source_type in ('PRODUCT_PHOTO', 'FAMILY_PHOTO', 'PURCHASE_DOCUMENT', 'PLANNER_ATTACHMENT'));
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'ck_media_legacy_target_type') then
        alter table media_legacy_source add constraint ck_media_legacy_target_type check (
            target_type in ('PRODUCT', 'PRODUCT_FAMILY', 'PURCHASE_ORDER', 'PLANNER_ITEM'));
    end if;
    if not exists (select 1 from pg_constraint where conrelid = 'media_legacy_source'::regclass
            and conname = 'ck_media_legacy_role') then
        alter table media_legacy_source add constraint ck_media_legacy_role
            check (role in ('CATALOGUE', 'QUOTE', 'INVOICE', 'INTERNAL'));
    end if;

    if to_regclass('sales_order') is not null and not exists (
            select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'fk_sales_document_media_order') then
        alter table sales_document_media_snapshot add constraint fk_sales_document_media_order
            foreign key (order_id) references sales_order(id) on delete cascade;
    end if;
    if to_regclass('product') is not null and not exists (
            select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'fk_sales_document_media_product') then
        alter table sales_document_media_snapshot add constraint fk_sales_document_media_product
            foreign key (product_id) references product(id) on delete restrict;
    end if;
    if to_regclass('photo_blob') is not null and not exists (
            select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'fk_sales_document_media_blob') then
        alter table sales_document_media_snapshot add constraint fk_sales_document_media_blob
            foreign key (storage_key) references photo_blob(storageKey) on delete restrict;
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'uk_sales_document_media_snapshot') then
        alter table sales_document_media_snapshot add constraint uk_sales_document_media_snapshot
            unique (order_id, product_id, role);
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'ck_sales_document_media_role') then
        alter table sales_document_media_snapshot add constraint ck_sales_document_media_role
            check (role in ('QUOTE', 'INVOICE'));
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'ck_sales_document_media_version_pair') then
        alter table sales_document_media_snapshot
            add constraint ck_sales_document_media_version_pair check (
                (media_asset_id is null and media_version_id is null)
                or (media_asset_id is not null and media_version_id is not null));
    end if;
    if not exists (select 1 from pg_constraint
            where conrelid = 'sales_document_media_snapshot'::regclass
            and conname = 'fk_sales_document_media_version') then
        alter table sales_document_media_snapshot add constraint fk_sales_document_media_version
            foreign key (media_version_id, media_asset_id)
            references media_version(id, asset_id) on delete restrict;
    end if;

    -- Composite constraints ensure a pinned/current version belongs to the same asset.
    if not exists (select 1 from pg_constraint where conrelid = 'media_asset'::regclass
            and conname = 'fk_media_asset_current_version') then
        alter table media_asset add constraint fk_media_asset_current_version
            foreign key (current_version_id, id) references media_version(id, asset_id)
            deferrable initially deferred;
    end if;
end $$;

create index if not exists idx_media_asset_updated on media_asset(updated_at);
create index if not exists idx_media_asset_archived on media_asset(archived);
create index if not exists idx_media_version_storage_key on media_version(storage_key);
create index if not exists idx_media_version_thumbnail_storage_key on media_version(thumbnail_storage_key);
create index if not exists idx_media_link_target_role on media_link(target_type, target_id, role);
create index if not exists idx_media_link_asset on media_link(asset_id);
create unique index if not exists uk_media_link_primary_target_role
    on media_link(target_type, target_id, role) where primary_slot = 1;
create index if not exists idx_media_legacy_source_asset on media_legacy_source(asset_id);
create index if not exists idx_media_legacy_source_target
    on media_legacy_source(target_type, target_id);
create index if not exists idx_sales_document_media_storage
    on sales_document_media_snapshot(storage_key);
