-- Folders, public links and the web-size rendition arrived after the media
-- manager migration was written. Additive and rerunnable: columns and tables
-- are only created when missing, so a database prepared by Hibernate's
-- "update" strategy (production) passes untouched and a "validate" database
-- (test) gains exactly what the entities expect.

alter table media_asset add column if not exists folder_id bigint;

create table if not exists media_folder (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    parent_id bigint,
    created_at timestamp with time zone not null,
    created_by varchar(64)
);
create index if not exists idx_media_folder_parent on media_folder(parent_id);

create table if not exists media_share (
    id bigint generated by default as identity primary key,
    asset_id bigint not null,
    token varchar(64) not null,
    created_at timestamp with time zone not null,
    created_by varchar(64),
    revoked_at timestamp with time zone,
    downloads bigint not null default 0
);
create index if not exists idx_media_share_asset on media_share(asset_id);
create unique index if not exists idx_media_share_token on media_share(token);

alter table media_version add column if not exists web_storage_key varchar(80);
alter table media_version add column if not exists web_content_type varchar(120);
alter table media_version add column if not exists web_size_bytes bigint;
alter table media_version add column if not exists web_width_px integer;
alter table media_version add column if not exists web_height_px integer;
