-- Page views of the public website, posted by the site's edge function.
-- No personal data: the visitor column is a daily rotating hash made at the
-- edge. Rerunnable: created only when missing.

create table if not exists website_visit (
    id bigint generated by default as identity primary key,
    occurred_at timestamp with time zone not null,
    visitor varchar(64) not null,
    path varchar(255) not null,
    page_kind varchar(24) not null,
    locale varchar(8),
    country varchar(2),
    city varchar(80),
    referrer_host varchar(120),
    source varchar(64),
    medium varchar(64),
    campaign varchar(120),
    device varchar(12) not null,
    screen_width integer
);
create index if not exists idx_website_visit_occurred on website_visit(occurred_at);
create index if not exists idx_website_visit_visitor on website_visit(visitor, occurred_at);
