BEGIN;
ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS purpose varchar(32);
ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS source_purchase_order_id bigint;
ALTER TABLE sales_order ADD COLUMN IF NOT EXISTS payment_plan varchar(40);
CREATE TABLE IF NOT EXISTS sales_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id bigint NOT NULL REFERENCES sales_order(id),
    amount_eur numeric(19,2) NOT NULL,
    received_at timestamptz NOT NULL,
    time_zone varchar(64) NOT NULL,
    reference varchar(500),
    recorded_at timestamptz NOT NULL,
    actor varchar(255),
    legacy boolean NOT NULL DEFAULT false,
    voided_at timestamptz,
    legacy_key varchar(80) UNIQUE,
    CONSTRAINT sales_payment_positive_amount CHECK (amount_eur > 0)
);
CREATE INDEX IF NOT EXISTS sales_payment_order_received_idx ON sales_payment(sales_order_id, received_at);
CREATE TABLE IF NOT EXISTS partner_settlement_snapshot (
    sales_order_id bigint PRIMARY KEY REFERENCES sales_order(id),
    purchase_order_id bigint NOT NULL REFERENCES purchase_order(id),
    revenue_eur numeric(19,2) NOT NULL,
    cost_eur numeric(19,2) NOT NULL,
    advance_eur numeric(19,2) NOT NULL
);
CREATE INDEX IF NOT EXISTS partner_settlement_purchase_idx ON partner_settlement_snapshot(purchase_order_id);
COMMIT;
