-- The line of landed costs a product carried, one row per container it was set from; never pruned.
create table if not exists product_cost_history (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    landed_unit_eur numeric(19,4) not null,
    previous_landed_unit_eur numeric(19,4),
    source varchar(120),
    purchase_order_id bigint,
    quantity integer,
    exw_price numeric(19,4),
    exw_currency varchar(3),
    applied_at timestamp(6) with time zone not null,
    applied_by varchar(80)
);
create index if not exists product_cost_history_product_idx on product_cost_history (product_id, applied_at desc);
