-- Recurring cost definitions booked by the server, bank readings, and the link from a booked cost to its definition.
alter table company_cost add column if not exists recurring_cost_id bigint;

create table if not exists recurring_cost (
    id bigint generated by default as identity primary key,
    name varchar(300) not null,
    category varchar(60) not null,
    party varchar(200),
    amount_excl_eur numeric(19,2) not null,
    vat_pct numeric(5,2),
    sales_channel varchar(40),
    interval_code varchar(20) not null,
    start_date date not null,
    end_date date,
    next_date date,
    active boolean,
    auto_paid boolean,
    reference varchar(120),
    notes varchar(2000),
    last_booked_on date,
    created_at timestamp(6) with time zone
);

create table if not exists bank_balance (
    id bigint generated by default as identity primary key,
    account varchar(120) not null,
    balance_date date not null,
    balance_eur numeric(19,2) not null,
    notes varchar(2000),
    created_at timestamp(6) with time zone
);
