-- Sales channels on documents (direct, website, partner, TICA, fair) and the company's own costs.
alter table sales_order add column if not exists sales_channel varchar(40);

create table if not exists company_cost (
    id bigint generated by default as identity primary key,
    cost_date date not null,
    category varchar(60) not null,
    description varchar(300) not null,
    party varchar(200),
    amount_excl_eur numeric(19,2) not null,
    vat_pct numeric(5,2),
    reference varchar(120),
    paid_on date,
    sales_channel varchar(40),
    notes varchar(2000),
    created_at timestamp(6) with time zone
);
