-- Durable anonymous-form abuse controls, idempotency, contact intake and notification outbox.
--
-- Anti-abuse identifiers are HMAC-SHA256 values only: no raw IP address, e-mail address,
-- challenge token, form token or request payload is stored in these technical tables.
-- This migration is additive, rerunnable and safe to apply before the application code.

begin;

create table if not exists public_form_lock (
    id integer primary key
);

insert into public_form_lock (id)
select generate_series(0, 63)
on conflict (id) do nothing;

create table if not exists public_form_rate_bucket (
    id varchar(64) primary key,
    action varchar(32) not null,
    key_type varchar(16) not null,
    key_hash varchar(64) not null,
    window_started_at timestamp with time zone not null,
    request_count integer not null,
    expires_at timestamp with time zone not null
);

create index if not exists idx_public_form_rate_expiry
    on public_form_rate_bucket (expires_at);

create table if not exists public_form_submission (
    id varchar(64) primary key,
    purpose varchar(16) not null,
    payload_hash varchar(64) not null,
    response_json text not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null
);

create index if not exists idx_public_form_submission_expiry
    on public_form_submission (expires_at);

create table if not exists contact_inquiry (
    id bigint generated by default as identity primary key,
    reference varchar(32) not null unique,
    status varchar(16) not null,
    language varchar(4) not null,
    topic varchar(32) not null,
    contact_name varchar(120) not null,
    email varchar(254) not null,
    company_name varchar(160),
    phone varchar(50),
    message varchar(2000) not null,
    source_page varchar(500),
    privacy_accepted_at timestamp with time zone not null,
    privacy_policy_version varchar(40) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index if not exists idx_contact_inquiry_status_created
    on contact_inquiry (status, created_at);
create index if not exists idx_contact_inquiry_created_id
    on contact_inquiry (created_at, id);
create unique index if not exists idx_contact_inquiry_reference
    on contact_inquiry (reference);

create table if not exists contact_notification_outbox (
    id bigint generated by default as identity primary key,
    inquiry_id bigint not null unique references contact_inquiry (id),
    status varchar(16) not null,
    attempt_count integer not null,
    next_attempt_at timestamp with time zone not null,
    last_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    last_error varchar(300)
);

create index if not exists idx_contact_outbox_due
    on contact_notification_outbox (status, next_attempt_at);

commit;
